### ISSUE TITLE
"NHNetworkTime.h file not found"

### ISSUE THREAD

**Issue by DragonMeistah** [huynguyencong/NHNetworkTime#11]
After installing cocoapods by adding `pod 'NHNetworkTime', :git => 'https://github.com/huynguyencong/NHNetworkTime.git'` to my podfile and adding `#import "NHNetworkTime.h"` to my bridging header i consistently get error  "NHNetworkTime.h file not found". I tried using `pod 'NHNetworkTime` in my podfile instead but it still didn't work. I have tried with AND without `use_frameworks!` and same result each time. Any advice?

**Comment by huynguyencong** [comment]
I can't reproduce your problem. I try to pod use both pod spec, it is ok. 
Can you give me detail how to produce this error?
Can you provide error message when you use `pod 'NHNetworkTime'`?

**Comment by huynguyencong** [comment]
Fixed. Please update version 1.6 and read Readme file to know how to import
