### ISSUE TITLE
Issue in pure Swift project with Cocoapods 1.0.0

### ISSUE THREAD

**Issue by gonghao** [huynguyencong/NHNetworkTime#13]
When use `use_frameworks!` in a pure Swift project with Cocoapods 1.0.0, there is an issue:

`/Users/xxx/Library/Developer/Xcode/DerivedData/xxx/Build/Products/Debug-iphoneos/NHNetworkTime/NHNetworkTime.framework/Headers/NHNetAssociation.h:16:9: error: 'CocoaAsyncSocket/GCDAsyncUdpSocket.h' file not found`

**Comment by huynguyencong** [comment]
I have no problem with Cocoapods 1.0.0 and Swift project use `use_frameworks!`. Do you call `import NHNetworkTime` in source file use `NHNetworkClock`?
Does anyone else has same issue?

**Comment by gonghao** [comment]
Yes, of course.

**Comment by gonghao** [comment]
@huynguyencong I found it something wrong because of upgrading to Cocoapods 1.0.0 and the cached wrong module file in `DerivedData` directory. I cleaned the files, and it works now.

Thanks.

**Comment by huynguyencong** [comment]
OK, thank you
