### ISSUE TITLE
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/443F9124-BDDA-452E-A0E3-E73C81930BC0/timeTesting.app> (loaded)' with name 'Rkk-g4-vge-view-TV7-kw-gIS' and directory 'Main.storyboardc''

### ISSUE THREAD

**Issue by unittesting0** [huynguyencong/NHNetworkTime#15]
I'm getting an error while using NHNetworkTime

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/443F9124-BDDA-452E-A0E3-E73C81930BC0/timeTesting.app> (loaded)' with name 'Rkk-g4-vge-view-TV7-kw-gIS' and directory 'Main.storyboardc''

May i know what am I doing wrong?
## My question is How can i refresh the time inside the viewController, if the time has not be loaded after the timeout?

Sometimes I get Critical failure: the LastResort font is unavailable.

**Comment by huynguyencong** [comment]
You can call `synchronize` method of `NHNetworkClock` class.
The error of you loading nib, I think it is not concern with `NHNetworkTime`
