### ISSUE TITLE
Library not working on IPv6 Network

### ISSUE THREAD

**Issue by Vytek** [huynguyencong/NHNetworkTime#16]
After review my app on Apple there is problem about IPv6 network socket.

I use only NHNetworkTime.

See for example: https://github.com/jbenet/ios-ntp/commit/c6e0ab837d1b539ed1f5146645ce823238c5ea40

Let me know.
Regards.

**Comment by huynguyencong** [comment]
I don't know what the link you post you mean? Have you tested it on IPv6?
