### ISSUE TITLE
Version conflict in POD

### ISSUE THREAD

**Issue by KRISHNAIOS** [huynguyencong/NHNetworkTime#17]
As NHNetworkTime uses CocoaAsyncSocket (<= 7.4.1) and the other library which i'm using uses CocoaAsyncSocket (~> 7.4.3), I am not able to integrate successfully NHNetworkTime. How could i solve it?

**Comment by huynguyencong** [comment]
Please do as this answer:
http://stackoverflow.com/questions/19039111/using-pods-with-conflicting-afnetworking-dependencies
- Fork NHNetworkTime to your Github
- Update version of CocoaAsyncSocket in Pod spec to version you want.
- Edit your Podfile, specify it directly to your github fork

Thank for using my open source

**Comment by huynguyencong** [comment]
Merged it. Thanks!
