### ISSUE TITLE
Hardcoded NTP Pool names

### ISSUE THREAD

**Issue by jpbede** [huynguyencong/NHNetworkTime#21]
Please don't hard code NTP Pool (pool.ntp.org) hostnames. It could be possible that one of your users has a bad implementation and caused considerable havoc on the system. Leave the list empty and reference http://www.pool.ntp.org/vendors.html

**Comment by huynguyencong** [comment]
You can customize your host list by add a file name "ntp.hosts" to your project. It's a text file contain hosts, each host in one line.
See the code in NHNetworkClock::createAssociations

**Comment by huynguyencong** [comment]
https://github.com/huynguyencong/NHNetworkTime#custom-time-server
