### ISSUE TITLE
Time is not synchronised if we call synchronize multiple times

### ISSUE THREAD

**Issue by Ravi-Kiran-HR** [huynguyencong/NHNetworkTime#22]
when we call  [[NHNetworkClock sharedNetworkClock]synchronize];  multiple times ( some 4 times )

[NSDate networkDate] will always return the local time (time is not synchronised) and in the console we are getting the following error 

dnssd_clientstub deliver_request: socketpair failed 24 (Too many open files)

**Comment by nickbarbato** [comment]
same issue...

**Comment by MchlG** [comment]
same issue here

**Comment by huynguyencong** [comment]
It's not necessary calling synchronize multiple time. Just call once then wait for the network time
