### ISSUE TITLE
"GCDAsyncUdpSocket.h" not found

### ISSUE THREAD

**Issue by lajz** [huynguyencong/NHNetworkTime#23]
While using you library  nothing works as it says that "GCDAsyncUdpSocket.h" file not found.
Any help?

**Comment by MchlG** [comment]
grab it from here and add it to your project https://github.com/jbenet/ios-ntp/tree/master/network-udp

**Comment by huynguyencong** [comment]
Have you still had the problem?

**Comment by lajz** [comment]
No, although thank you for the follow up.

**Comment by huynguyencong** [comment]
Thank you. Sorry for my late response.
