### ISSUE TITLE
Crash with error "EXC_BAD_ACCESS"

### ISSUE THREAD

**Issue by mahmudulhasancsedu5** [huynguyencong/NHNetworkTime#29]
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000001
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x183d00908 objc_msgSend + 8
1  NHNetworkTime                  0x105ef3eec -[NHNetworkClock finishAssociations] + 244
2  NHNetworkTime                  0x105ef3334 -[NHNetworkClock reset] + 48
3  NHNetworkTime                  0x105ef3fc8 -[NHNetworkClock synchronize] + 32
4  Foundation                     0x1854961bc -[__NSObserver _doit:] + 312
5  CoreFoundation                 0x184ac4c3c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
6  CoreFoundation                 0x184ac41b8 _CFXRegistrationPost + 428
7  CoreFoundation                 0x184ac3f14 ___CFXNotificationPost_block_invoke + 216
8  CoreFoundation                 0x184b4184c -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1408
9  CoreFoundation                 0x1849faf38 _CFXNotificationPost + 384
10 Foundation                     0x18546bbbc -[NSNotificationCenter postNotificationName:object:userInfo:] + 68
11 UIKit                          0x18eb2d238 -[UIApplication significantTimeChange] + 120
12 CoreFoundation                 0x184ac4c3c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
13 CoreFoundation                 0x184ac4b80 ___CFXRegistrationPost_block_invoke + 64
14 CoreFoundation                 0x184adb2bc __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 20
15 CoreFoundation                 0x184adaa7c __CFRunLoopDoBlocks + 264
16 CoreFoundation                 0x184ad8abc __CFRunLoopRun + 2004
17 CoreFoundation                 0x1849f8da8 CFRunLoopRunSpecific + 552
18 GraphicsServices               0x1869de020 GSEventRunModal + 100
19 UIKit                          0x18ea18758 UIApplicationMain + 236
20 GearManager                    0x1045405f0 main (main.m:26)
21 libdyld.dylib                  0x184489fc0 start + 4

**Comment by huynguyencong** [comment]
Could you please provide more info about it?
