### ISSUE TITLE
Time sync completion block never get called

### ISSUE THREAD

**Issue by zenghaojim33** [huynguyencong/NHNetworkTime#3]
Hello, I clone the project and test it on my iphone6.  I found that the sync block never get called thus the text label always shows "Time is not synchronized",and both time babe shows the wrong local time.  I ping the ntp server seems the network is fine.  Any idea why this happened?  Thanks.

**Comment by huynguyencong** [comment]
May be that is a problem with the Example. I've just updated new version, improve the example. Let me know if the issue still happen.
Thank you!

**Comment by zenghaojim33** [comment]
Wow ok I know what happened.  I'm using shadowsocks (a http proxy that allows me to visit the blocked website) on my iPhone and somehow it affects this example as well.  I turned the proxy off and everything works just fine.  My bad.

**Comment by huynguyencong** [comment]
OK, thank you. I will close that issue. So, it is not my code error
