### ISSUE TITLE
Got crash issue from fabric.

### ISSUE THREAD

**Issue by developeraminul** [huynguyencong/NHNetworkTime#31]
Platform: ios
 Issue #: 1061
 Issue ID: 5ba553daf8b88c2963c7df84
 Session ID: 68ceead1616b476fb390e1b15bdce378_DNE_0_v2
 Date: 2018-09-28T14:44:00Z
 OS Version: 11.4.1 (15G77)
 Device: iPhone 6s
 RAM Free: 4.7%
 Disk Free: 41.1%

 Crashed: NSOperationQueue 0x1c1024040 (QOS: UNSPECIFIED)
0  libsystem_platform.dylib       0x18159aa80 _platform_memmove + 176
1  CoreFoundation                 0x18184ac3c -[__NSArrayM insertObject:atIndex:] + 356
2  CoreFoundation                 0x18184ac3c -[__NSArrayM insertObject:atIndex:] + 356
**3  NHNetworkTime                  0x104463d54 -[NHNetworkClock createAssociations] + 1340**
4  CoreFoundation                 0x181986580 __invoking___ + 144
5  CoreFoundation                 0x181865748 -[NSInvocation invoke] + 284
6  Foundation                     0x1823a7308 -[NSInvocationOperation main] + 40
7  Foundation                     0x1822e7cac -[__NSOperationInternal _start:] + 848
8  Foundation                     0x1823a876c __NSOQSchedule_f + 404
9  libdispatch.dylib              0x181270a60 _dispatch_client_callout + 16
10 libdispatch.dylib              0x181278e94 _dispatch_continuation_pop$VARIANT$mp + 424
11 libdispatch.dylib              0x1812777cc _dispatch_async_redirect_invoke$VARIANT$mp + 604
12 libdispatch.dylib              0x18127dcac _dispatch_root_queue_drain + 588
13 libdispatch.dylib              0x18127d9fc _dispatch_worker_thread3 + 120
14 libsystem_pthread.dylib        0x1815a3fac _pthread_wqthread + 1176
15 libsystem_pthread.dylib        0x1815a3b08 start_wqthread + 4

**Comment by huynguyencong** [comment]
Could you please provide more detail for me? For example, how you use this lib in your project.

**Comment by developeraminul** [comment]
I use cocoapod to configure this lib in our project. From the Podfile.lock file I found that NHNetworkTime version is 1.7. We found several crash in this lib but frequency is not so high (10-20).
