### ISSUE TITLE
Using NHNetworkTime for Cocoa application

### ISSUE THREAD

**Issue by shaandsingh** [huynguyencong/NHNetworkTime#32]
Hi there—I'm looking to use NHNetworkTime for a macOS application. Other than removing references to UIKit, do you have any other suggestions for my conversion? I replaced the UIApplicationSignificantTimeChangeNotification with NSSystemClockDidChangeNotification and ~~commented out~~ similarly replaced the foreground/background notifications.

**Comment by huynguyencong** [comment]
This open source doesn't support other platform than iOS. So please forked it or add it manually then update it as you mentioned. Thank you!
