### ISSUE TITLE
Did not update correct time after app is moved from background to foreground

### ISSUE THREAD

**Issue by baigozin** [huynguyencong/NHNetworkTime#33]
When app is moving to the background, UIApplicationDidEnterBackgroundNotification is observed and every NHNetAssociation execute [self finish], whitch execte [self unregisterObservations], which remove all observers, including UIApplicationWillEnterForegroundNotification.

So, after app is on foreground, there is no observers to make  [self enable] for NHNetAssociation's objects. 

Workaround - execte [[NHNetworkClock sharedNetworkClock] synchronize] in applicationDidBecomeActive:, not in didFinishLaunchingWithOptions: method of appDelegate.

**Comment by huynguyencong** [comment]
Thanks for you feedback. Just fixed it. Please update new version in the next day.
