### ISSUE TITLE
timeAssociations is NSMutableArray, should be copied or make atomic.

### ISSUE THREAD

**Issue by sbhhbs** [huynguyencong/NHNetworkTime#4]
timeAssociations is NSMutableArray, should be copied or make atomic.
Otherwise will cause :
**\* Collection <__NSArrayM: 0x157813f20> was mutated while being enumerated.

Thread : Fatal Exception: NSGenericException
0  CoreFoundation                 0x184655900 __exceptionPreprocess
1  libobjc.A.dylib                0x183cc3f80 objc_exception_throw
2  CoreFoundation                 0x184655334 -[NSException name]
3  Musical.ly                     0x1010801d8 -[NHNetworkClock finishAssociations](NHNetworkClock.m:193)
4  Musical.ly                     0x10107f270 -[NHNetworkClock reset](NHNetworkClock.m:55)
5  Musical.ly                     0x10108034c -[NHNetworkClock syncWithComplete:](NHNetworkClock.m:203)

**Comment by huynguyencong** [comment]
Merged your pull request
Thank you
