### ISSUE TITLE
NSOperationQueue

### ISSUE THREAD

**Issue by tspent** [huynguyencong/NHNetworkTime#7]
I have some issues when multiple times syncWithCompletion is called. Some time nothing happens.
So i start looking around your code.
Every time someone is calling syncWithCompletion your are allocating a new NSOperationQueue.
At your reset it will be wise to cancel the scheduled operations that you are adding.
I suggest a strong reference for  OperationQueue and every time someone is calling a sync to cancel all schedule operations. 
Make sense?

**Comment by DragonMeistah** [comment]
+1!

**Comment by huynguyencong** [comment]
I replied issue from @DragonMeistah . May be it is also the answer for your question.
[Why syncWithCompleteBlock not recommended?](https://github.com/huynguyencong/NHNetworkTime/issues/8)
Summary: Don't call `syncWithCompletion` multiple times (I removed the completion block in newest version). Should use `kNHNetworkTimeSyncCompleteNotification` to receive "update time successfully" event

**Comment by huynguyencong** [comment]
Updated. Please review read me file

**Comment by tspent** [comment]
Ok make sense, no need to have access to syncWithCompletion!
